CONSTRUCT {
    []
        dwc:scientificName           ?fullname;
        dwc:scientificNameAuthorship ?authorname;
        schema:sameAs                ?page;
        .
}
WHERE {
    ?c
        api:valid_guid      ?id;
        api:scientificname  ?scientificname;
        api:authority       ?author.
        
	OPTIONAL { ?c api:url ?url }

    bind (sms:formatAuthorName(?author) AS ?authorname)
    bind (concat(?scientificname, " ", ?authorname) AS ?fullname)
    bind (IRI(?url) AS ?page)
}

# Format author name removing extra spaces at beginning and end of the name and after a dot
# " (Bloch, 1782)" => "(Bloch, 1782)";
# "A. Gray" => "A.Gray"
function sms:formatAuthorName(?author) {
    replace(replace(?author, "(\\. )", "."), "(^ *)|( *$)", "")
}
