INSERT {
    ?taxonUri dwc:taxonID ?id;
        dwc:scientificName ?scientificname;
        taxrefp:hasRank ?rankUri;
        skos:broader ?parentTaxon;
.
}
WHERE {
    ?c api:AppelTaxonParent [
        api:CdAppelTaxon ?id
     ];

    bind(IRI(concat("http://example.org/sparql-ms/sandre/getTaxaByID?id=", ?id)) AS ?service)
    SERVICE ?service {
        ?taxonUri dwc:scientificName ?scientificname;
            taxrefp:hasRank ?rankUri;
            skos:broader ?parentTaxon.
    }

}
