PREFIX dwc: <http://rs.tdwg.org/dwc/terms/>
PREFIX schema: <http://schema.org/>
PREFIX taxrefp: <http://taxref.mnhn.fr/lod/property/>

#Select scientific name, taxonomic rank and link to the webpage of the direct parent of a taxon from the second service,
#if name or rank are different from the ones in the first service
SELECT ?name ?rank ?page WHERE {
    SERVICE <<%= mainService %>> {
        #From the whole classification of the taxon, pick the most proximate parent, given its URI
        <<%= params.parentUri %>> dwc:scientificName ?name1;
                                  taxrefp:hasRank ?rank1;
    }
    # Query the second service (that returns only the parentTaxon) to get scientific name, taxonomic rank and, optionally, link to taxon webpage
    SERVICE <<%= service.url %>> {
        ?c dwc:scientificName ?name;
           taxrefp:hasRank ?rank.
        OPTIONAL{  ?c schema:sameAs ?page}.
    }
    FILTER (?name1 != ?name || ?rank1 != ?rank)
}