PREFIX taxrefp: <http://taxref.mnhn.fr/lod/property/>

#Select the habitats in the first service that are not present in the second one
SELECT ?service ?habitat WHERE{
   SERVICE <<%= mainService %>> {
       [] taxrefp:habitat ?habitat.
   } MINUS {
        SERVICE <<%= service.url %>> {
                 [] taxrefp:habitat ?habitat.
        }
   }
   BIND( "<%= service.label %>" AS ?service)
}