CONSTRUCT {
    []
        dwc:scientificNameAuthorship ?authorname;
        dwc:scientificName ?fullname;
        schema:sameAs ?wormsPage;
        .
}
WHERE {
    ?content
        api:AphiaID ?id;
        api:authority ?author;
        api:scientificname ?scientificname;
        api:url ?url;
        .
        
    bind(sms:formatAuthorName(?author) AS ?authorname)
    bind(concat(?scientificname, " ", ?authorname) AS ?fullname)
    bind (IRI(?url) AS ?wormsPage)
}

# Format author name removing extra spaces at beginning and end of the name and after a dot
# " (Bloch, 1782)" => "(Bloch, 1782)";
# "A. Gray" => "A.Gray"
function sms:formatAuthorName(?author){
    replace(replace(?author, "(\\. )", "."), "(^ *)|( *$)", "")
}