CONSTRUCT {
    []
        dwc:scientificNameID         ?id;
        dwc:scientificNameAuthorship ?authorname;
        dwc:scientificName           ?scientificname;
        dwc:taxonomicStatus            ?status;
        dwc:taxonRemarks            ?unacceptreason;
        schema:sameAs                ?wormsPage;
        .
}
WHERE {
    ?c
        api:AphiaID         ?id;
        api:authority       ?author;
        api:scientificname  ?scientificname;
        api:url             ?url;
        .
    OPTIONAL { ?c api:unacceptreason           ?unacceptreason }
    OPTIONAL { ?c api:status           ?status }

    bind(sms:formatAuthorName(?author) AS ?authorname)
    bind (IRI(?url) AS ?wormsPage)
}

# Format author name removing extra spaces at beginning and end of the name and after a dot
# " (Bloch, 1782)" => "(Bloch, 1782)";
# "A. Gray" => "A.Gray"
function sms:formatAuthorName(?author) {
    replace(replace(?author, "(\\. )", "."), "(^ *)|( *$)", "")
}
