PREFIX taxrefp: <http://taxref.mnhn.fr/lod/property/>.

CONSTRUCT {
    ?taxonUri a dwc:Taxon;

        dwc:scientificName           ?scientificName;
        dwc:scientificNameID         ?id;
        dwc:scientificNameAuthorship ?authorshipName;
        dwc:taxonomicStatus          ?status;

        dwc:kingdom                  ?kingdom;
        dwc:phylum                   ?phylum;
        dwc:class                    ?class;
        dwc:order                    ?order;
        dwc:family                   ?family;
        dwc:genus                    ?genus;

        schema:sameAs                ?page;
		.
}
WHERE {
    ?results                api:taxon ?result.
    ?result
        api:sis_id          ?id;
        api:authority      ?authorship;
        api:scientific_name        ?scientificName.

    OPTIONAL { ?result api:kingdom_name         ?kingdom }
    OPTIONAL { ?result api:phylum_name          ?phylum }
    OPTIONAL { ?result api:class_name           ?class }
    OPTIONAL { ?result api:order_name           ?order }
    OPTIONAL { ?result api:family_name          ?family }
    OPTIONAL { ?result api:genus_name           ?genus}

    bind (IRI(concat("http://example.org/ld/col/taxon/", ?id)) AS ?taxonUri)
    bind (IRI(concat("https://api.iucnredlist.org/api/v4/taxa/sis/", ?id)) AS ?page)
    
    bind (replace(?authorship, " &amp; ", " & ") AS ?authorshipName)

#    bind(IF(?is_Marine = "true"^^xsd:boolean, 1, 0) AS ?isMarine)
#    bind(IF(?is_Freshwater = "true"^^xsd:boolean, 1, 0) AS ?isFreshwater)
#    bind(IF(?is_Terrestrial  = "true"^^xsd:boolean, 1, 0) AS ?isTerrestrial)

}

# Format author name removing extra spaces at beginning and end of the name and after a dot
# and moving basionymName (in round brackets at the end of the name) to the beginning of the name (like in TAXREF)
# " (Bloch, 1782)" => "(Bloch, 1782)";
# "A. Gray" => "A.Gray"
# "E.Mey., 1839 (L.)" => "(L.) E.Mey., 1839"
#function sms:formatAuthorName(?author) {
#    LET (?basionym = IF(regex(?author, "\\(.*\\)$"), replace(?author, "^.*(\\(.*\\))$", "$1"), "")) {
#        LET (?author = concat(?basionym , " ", replace(?author, "\\(.*\\)$", ""))) {
#            replace(replace(replace(?author, "amp;", ""), "(\\. )", "."), "(^ *)|( *$)", "")
#        }
#    }
#}
