CONSTRUCT {
    [] 
        a           schema:Thing;
        schema:url  ?uri;
        schema:name ?frname.
}
WHERE {
	?rank
        api:name ?name;
        api:taxrefUri ?taxrefUri.
    bind(IRI(?taxrefUri) AS ?uri)
    bind (STRLANG(?name, "fr") AS ?frname)
}